java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/tec/api-poc:latest'
  ingressHost: tec-api-poc-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: tec
#  Uncomment once the vault containing the app insights key has been set up
#  keyVaults:
#    tec:
#      secrets:
#        - name: AppInsightsInstrumentationKey
#          alias: azure.application-insights.instrumentation-key
  environment:
