server:
  port: ${SERVER_PORT:4013}
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
      group:
        readiness:
          include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.tecpoc.controllers
  writer-with-order-by-keys: true

spring:
  application:
    name: TEC API POC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tec}${DB_OPTIONS:}
    username: ${DB_USER_NAME:tec}
    password: ${DB_PASSWORD:tec}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 10000
      pool-name: TecPocHikariCP
      max-lifetime: 7200000
      connection-timeout: 30000
  flyway:
    enabled: true

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  client:
    id: ${IDAM_CLIENT_ID:tec}
    secret: ${IDAM_CLIENT_SECRET:123456}
    redirect_uri: ${IDAM_REDIRECT_URI:http://localhost:3000/oauth2/callback}
  s2s-auth:
    url: ${IDAM_S2S_AUTH_URL:http://localhost:4502}
    totp-secret: ${TEC_API_S2S_SECRET:AAAAAAAAAAAAAAAA}
    microservice: ${S2S_SERVICE_NAME:tec_api}

core_case_data:
  api:
    url: ${CCD_DATA_STORE_URL:http://localhost:4452}

tec:
  poc:
    local-idam: ${TEC_POC_LOCAL_IDAM:false}
