server:
  port: 8080
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
      group:
        readiness:
          include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.tecpoc.controllers
  writer-with-order-by-keys: true

spring:
  application:
    name: TEC API POC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tec}${DB_OPTIONS:}
    username: ${DB_USER_NAME:tec}
    password: ${DB_PASSWORD:tec}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 10000
      pool-name: TecPocHikariCP
      max-lifetime: 7200000
      connection-timeout: 30000
  flyway:
    enabled: true

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
